/**
 * Generate drizzle/0001_import_njdot_2017_data.sql from the raw NJDOT exports
 * in data/source/. The migration is committed, so `npm run db:migrate` never
 * needs this script; rerun it (`npm run db:generate-data`) only if the parsing
 * or cleanup rules in src/lib/source/ change, and review the diff.
 *
 * Future data refreshes should be new migrations, not edits to this one:
 * add the new export under data/source/, then create a new custom migration
 * with `npx drizzle-kit generate --custom --name=<name>` and generate into it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { getTableConfig, type SQLiteTable } from "drizzle-orm/sqlite-core";
import { bridges, stations } from "../src/db/schema";
import { parseBridges } from "../src/lib/source/bridges";
import { parseStations } from "../src/lib/source/stations";

const OUTPUT = "drizzle/0001_import_njdot_2017_data.sql";
const ROWS_PER_STATEMENT = 200;

function sqlValue(value: string | number | boolean | null): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`Non-finite number: ${value}`);
    return String(value);
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function inserts<T extends Record<string, string | number | boolean | null>>(
  table: SQLiteTable,
  records: T[],
): string[] {
  const { name, columns } = getTableConfig(table);
  // Map record keys (camelCase) to column names (snake_case), skipping `id`.
  const fields = columns
    .filter((column) => column.name !== "id")
    .map((column) => {
      const key = Object.entries(table).find(([, value]) => value === column)?.[0];
      if (!key) throw new Error(`No field for column ${column.name}`);
      return { key, column: column.name };
    });

  const statements: string[] = [];
  for (let i = 0; i < records.length; i += ROWS_PER_STATEMENT) {
    const rows = records
      .slice(i, i + ROWS_PER_STATEMENT)
      .map((record) => `(${fields.map(({ key }) => sqlValue(record[key])).join(", ")})`);
    statements.push(
      `INSERT INTO \`${name}\` (${fields.map(({ column }) => `\`${column}\``).join(", ")}) VALUES\n${rows.join(",\n")};`,
    );
  }
  return statements;
}

const stationRecords = parseStations(readFileSync("data/source/stations.txt", "latin1"));
const bridgeRecords = parseBridges(readFileSync("data/source/bridges.txt", "latin1"));

const header = `-- Import NJDOT's January 2017 station list and bridge inventory.
-- GENERATED by scripts/generate-data-migration.ts from data/source/*.txt; do not edit by hand.
-- ${stationRecords.length} stations, ${bridgeRecords.length} bridges.`;

const statements = [...inserts(stations, stationRecords), ...inserts(bridges, bridgeRecords)];
writeFileSync(OUTPUT, `${header}\n${statements.join("\n--> statement-breakpoint\n")}\n`);
console.log(`Wrote ${OUTPUT}: ${stationRecords.length} stations, ${bridgeRecords.length} bridges.`);
